package com.hao.m.greedao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hao.m.entity.data.AccountData;

import com.hao.m.greedao.AccountDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDataDaoConfig;

    private final AccountDataDao accountDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDataDaoConfig = daoConfigMap.get(AccountDataDao.class).clone();
        accountDataDaoConfig.initIdentityScope(type);

        accountDataDao = new AccountDataDao(accountDataDaoConfig, this);

        registerDao(AccountData.class, accountDataDao);
    }
    
    public void clear() {
        accountDataDaoConfig.clearIdentityScope();
    }

    public AccountDataDao getAccountDataDao() {
        return accountDataDao;
    }

}
